version: "3.10"
services:
  backend:
    build: ./backend
    command: gunicorn index:app -w 4 -b 0.0.0.0:5005
    ports:
      - "5005:5005"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
